### ISSUE TITLE
Remove bluebird dependency

### ISSUE THREAD

**Issue by felixfbecker** [stream-utils/stream-to-array#8]
This module depends on _both_ native-or-bluebird and bluebird, but only the former is actually required in code.

**Comment by jonathanong** [comment]
this was to keep `0.10` support w/o bumping a major version... i don't mind bumping another version and dropping `0.10` support now since it's so old

**Comment by jonathanong** [comment]
meh minor's fine.

**Comment by felixfbecker** [comment]
It doesn't matter for me but I stumbled across this and found it odd :)

**Comment by felixfbecker** [comment]
Shouldn't it be a patch version though?

**Comment by jonathanong** [comment]
dunno. kind of breaking, kind of a feature, kind of a bug fix. when in doubt, bump minor!

**Comment by felixfbecker** [comment]
Well native-or-bluebird has was already used, the only change is in package.json ^^
